batch_size: 64
dropout_prob: 0
embed_init_range: 0.1
embed_size: 512
grad_clip: null
learning_rate:
- 0.1
- 0.85
- 10
num_epochs: 10
num_eval_steps: 1000
num_layers: 1
num_steps: 7
rnn_type: srn
shuffle_per_epoch: true
train_percent: 0.9
