import math
from typing import Tuple, List
import networkx as nx
from collections import defaultdict

from traindsms.dsms.network import NetworkBaseClass
from traindsms.params import LONParams

VERBOSE = True


class LON(NetworkBaseClass):
    """
    co-occurrence graph, generated by joining linear sentence sequence by shared words
    """

    def __init__(self,
                 params: LONParams,
                 vocab: Tuple[str],
                 seq_tok: List[List[str]],
                 ):
        NetworkBaseClass.__init__(self)

        self.params = params
        self.vocab = vocab
        self.seq_tok = seq_tok

        self.freq_dict = defaultdict(int)
        self.co_mat = None

    def train(self):

        network_edges = []
        network_nodes = []
        for tokens in self.seq_tok:
            edges = []
            for i in range(len(tokens) - 1):
                edges.append((tokens[i],tokens[i+1]))
            for token in tokens:
                if token not in self.freq_dict:
                    self.freq_dict[token] = 1
                else:
                    self.freq_dict[token] = self.freq_dict[token] + 1
            network_edges.extend(edges)
            network_nodes.extend(tokens)

        self.node_list = list(set(network_nodes))

        network_edge_dict = {}
        for edge in network_edges:
            if edge in network_edge_dict:
                network_edge_dict[edge] = network_edge_dict[edge] + 1
            else:
                network_edge_dict[edge] = 1

        weighted_network_edge = []
        for edge in network_edge_dict:
            weighted_network_edge.append(edge + (math.log10(network_edge_dict[edge] + 1),))

        if VERBOSE:
            print()
            print('Weighted Edges:')
            for edge in weighted_network_edge:
                print(self.node_list.index(edge[0]), self.node_list.index(edge[1]), edge)
            print()

        # make network
        self.network = nx.Graph()
        self.network.add_weighted_edges_from(weighted_network_edge)

